[
    {
        "title": "Globular – Entangled Everything",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "91,797",
        "comments_count": "38",
        "url": "https://ektoplazm.com/free-music/globular-entangled-everything",
        "img": "https://ektoplazm.com/img/globular-entangled-everything-300x300.jpg",
        "tracks": [
            "Popping Out",
            "For The Time Being",
            "The Chalice",
            "Total Perspective Vortex",
            "One Step Beyond",
            "Dasein",
            "Be Patient Towards What Is Unsolved In Your Heart",
            "Dreamland Overflow",
            "Kaleidoscope Tribe",
            "This Strange Attractor",
        ],
        "media_bpm": ["65", "95", "58", "77", "69", "100", "74", "74", "67"],
    },
    {
        "title": "Zoungla – There Will Be Dub",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "37,066",
        "comments_count": "10",
        "url": "https://ektoplazm.com/free-music/zoungla-there-will-be-dub",
        "img": "https://ektoplazm.com/img/zoungla-there-will-be-dub-300x300.jpg",
        "tracks": [
            "Goodmorning Ozora",
            "Day Moon",
            "Homage To The Dub Masters",
            "Deep Sea Dubbin'",
            "Flower Sun",
            "Sunday",
            "Young Man 2",
            "Tune Out The World",
        ],
        "media_bpm": ["110", "86", "96", "70", "75", "95", "65", "93"],
    },
    {
        "title": "Globular – Holobiont",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "18,961",
        "comments_count": "4",
        "url": "https://ektoplazm.com/free-music/globular-holobiont",
        "img": "https://ektoplazm.com/img/globular-holobiont-300x300.jpg",
        "tracks": [
            "Tabula Rasa",
            "Emergent Resurgence",
            "[42]",
            "An Upwards Curve in the Horizon",
            "...and It Speaks of Everything",
            "The Might of Chondria",
            "Overcoming Occhiolism",
            "Temple of the Pollinator",
        ],
        "media_bpm": ["77", "77", "80", "96", "77", "77", "92"],
    },
    {
        "title": "Chilam Impacts 2",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "16,416",
        "comments_count": "10",
        "url": "https://ektoplazm.com/free-music/chilam-impacts-2",
        "img": "https://ektoplazm.com/img/va-chilam-impacts-2-300x300.jpg",
        "tracks": [
            "Duduk At Night",
            "Everything And Everywhere",
            "Stoned Badger",
            "Visions From The Forest",
            "Energy Of The Universe",
            "Octagonal Dub",
            "Stepping Stoned",
            "Ain Soph Aur",
            "An Upwords Curve In The Horizon",
            "Hena Madaliaki",
            "Long Journey",
            "Isle Of Dub",
            "Making Contact",
            "Jaded",
        ],
        "media_bpm": [
            "58",
            "90",
            "80",
            "150",
            "145",
            "136",
            "105",
            "92",
            "96",
            "120",
            "135",
            "85",
            "140",
            "120",
        ],
    },
    {
        "title": "Soul Curry",
        "styles": ["Bass Music", "Downtempo", "Psy Dub"],
        "download_count": "16,005",
        "comments_count": "1",
        "url": "https://ektoplazm.com/free-music/soul-curry",
        "img": "https://ektoplazm.com/img/va-soul-curry-300x300.jpg",
        "tracks": [
            "Ergonomic Ego",
            "We're Alive",
            "June",
            "Warpamily",
            "Time Takes The Time, Time Takes",
            "Memory",
            "Trance 909",
            "Stream of Mind",
            "Immersions",
            "Ebb & Flow",
            "Raum Dub",
            "Mise en Abyme",
            "The Snake With Limbs",
            "Desert Light",
            "ps.I.D.M",
            "Washed Up",
        ],
        "media_bpm": [
            "130",
            "90",
            "89",
            "120",
            "101",
            "127",
            "160",
            "110",
            "140",
            "84",
            "138",
            "85",
            "95",
            "85",
            "90",
            "92",
        ],
    },
    {
        "title": "Ghost In The Chill – Ghost In The Chill",
        "styles": ["Downtempo", "Glitch", "Psy Dub"],
        "download_count": "8,172",
        "comments_count": "3",
        "url": "https://ektoplazm.com/free-music/ghost-in-the-chill-ghost-in-the-chill",
        "img": "https://ektoplazm.com/img/ghost-in-the-chill-ghost-in-the-chill-300x300.jpg",
        "tracks": ["Aquarius", "Chaos Therapy", "Hozuki", "Baldub's Gate"],
        "media_bpm": ["84", "26", "82", "5", "120", "70"],
    },
    {
        "title": "Smörgåsbord Vol. 3: Porta-Party",
        "styles": ["Bass Music", "Downtempo", "Psy Dub"],
        "download_count": "23,500",
        "comments_count": "11",
        "url": "https://ektoplazm.com/free-music/smorgasbord-vol-3-porta-party",
        "img": "https://ektoplazm.com/img/va-smorgasbord-vol-3-300x300.jpg",
        "tracks": [
            "Sentient Salami",
            "Hubble Flow",
            "Jedi Shake",
            "Flum",
            "The Truth",
            "An Upwards Curve In The Horizon",
            "Fusion Age",
            "Orts Of Numbles",
            "The Freshmaker",
            "Magnifica S",
        ],
        "media_bpm": ["110", "90", "95", "122", "134", "96", "90", "94", "78", "108"],
    },
    {
        "title": "Step High – Celestial Colors",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "10,431",
        "comments_count": "9",
        "url": "https://ektoplazm.com/free-music/step-high-celestial-colors",
        "img": "https://ektoplazm.com/img/step-high-celestial-colors-300x300.jpg",
        "tracks": [
            "Red Shift",
            "Orange Glory",
            "Yellow Mood",
            "Green Path",
            "Blue Memory",
            "Indigo Children",
            "Purple Abundance",
            "Indigo Children",
        ],
        "media_bpm": ["101", "146", "146", "146", "146", "146", "121", "146"],
    },
    {
        "title": "Caleidisco – Infinite Variations of Black & White",
        "styles": ["Downtempo", "Experimental", "Psy Dub"],
        "download_count": "8,382",
        "comments_count": "7",
        "url": "https://ektoplazm.com/free-music/caleidisco-infinite-variations-of-black-white",
        "img": "https://ektoplazm.com/img/caleidisco-infinite-variations-of-black-and-white-300x300.jpg",
        "tracks": [
            "Wenkweur",
            "Pirnythia",
            "Squant",
            "Guzbloon",
            "Laflaysiil",
            "Exteisha",
            "Auros",
        ],
        "media_bpm": ["119", "191", "123", "160", "90", "100", "115"],
    },
    {
        "title": "Chilam Impacts",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "15,305",
        "comments_count": "13",
        "url": "https://ektoplazm.com/free-music/chilam-impacts",
        "img": "https://ektoplazm.com/img/va-chilam-impacts-300x300.jpg",
        "tracks": [
            "Transformation",
            "Prayer",
            "Great Prayer",
            "Even To Heaven",
            "Amara",
            "Endless Stairs",
            "Buddha Bass",
            "Avatamsaka Dub",
            "Brujería",
            "Tribal Impact",
            "Purification",
            "Twine",
            "Passe Par Trip",
            "Happy Bubbles And Deep Currents",
        ],
        "media_bpm": [
            "52",
            "80",
            "79",
            "120",
            "115",
            "124",
            "100",
            "98",
            "100",
            "90",
            "140",
            "95",
            "134",
            "67",
            "90",
            "75",
        ],
    },
    {
        "title": "Saluberrimae – Time Is A Flat Circle",
        "styles": ["Ambient", "Downtempo", "Psy Dub"],
        "download_count": "21,236",
        "comments_count": "17",
        "url": "https://ektoplazm.com/free-music/saluberrimae-time-is-a-flat-circle",
        "img": "https://ektoplazm.com/img/saluberrimae-time-is-a-flat-circle-300x300.jpg",
        "tracks": [
            "Trapped Inside",
            "Jesenné Prebúdzanie Do Letného Rána",
            "Jennifer Connelly",
            "Time Is A Flat Circle",
            "Loophole",
            "The Abyss",
            "Čiernobiela",
            "Frozen",
            "Večerná Ciga Na Balkóne",
            "Gestonkenflapped",
        ],
        "media_bpm": [
            "95",
            "80",
            "80",
            "70",
            "70",
            "95",
            "70",
            "110",
            "80",
            "70",
            "140",
        ],
    },
    {
        "title": "Monkey Puzzle – The Multi-Dimensional Satchel",
        "styles": ["Downtempo", "Organic", "Psy Dub"],
        "download_count": "18,766",
        "comments_count": "26",
        "url": "https://ektoplazm.com/free-music/monkey-puzzle-the-multi-dimensional-satchel",
        "img": "https://ektoplazm.com/img/monkey-puzzle-the-multi-dimensional-satchel-300x300.jpg",
        "tracks": [
            "3D",
            "Adventures In Mossland",
            "Dirty Sloth",
            "Isisn't",
            "Squid Beak",
        ],
        "media_bpm": ["83", "155", "132", "115", "7", "8", "75"],
    },
    {
        "title": "Cosmic Touch – Linked To The Essence",
        "styles": ["Bass Music", "Downtempo", "Psy Dub"],
        "download_count": "12,759",
        "comments_count": "9",
        "url": "https://ektoplazm.com/free-music/cosmic-touch-linked-to-the-essence",
        "img": "https://ektoplazm.com/img/cosmic-touch-linked-to-the-essence-300x300.jpg",
        "tracks": [
            "Linked To The Essence",
            "Ancestors March",
            "Shamans Warning",
            "Frequency Farmers Hut",
            "Ganipata Bass Recording",
            "Uncanny Feeling",
            "3rd Eye Open",
            "Flight Of The Medicine Hawk",
        ],
        "media_bpm": ["140", "70", "140", "140", "105", "70", "145", "70"],
    },
    {
        "title": "Inner Holographic Reality",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "12,888",
        "comments_count": "21",
        "url": "https://ektoplazm.com/free-music/inner-holographic-reality",
        "img": "https://ektoplazm.com/img/va-inner-holographic-reality-300x300.jpg",
        "tracks": [
            "Lullaby",
            "Holographic Nature",
            "Cosmic Playground",
            "11.11",
            "Dark Turned To Dawn",
            "Pagoda Skies",
            "Swampy Seance",
            "Perceptual Decay",
            "Something To Blog About",
            "Inspiration Dub",
            "Walking Alone In The Unknown",
            "Cry For A Butterfly",
            "For Our Future",
        ],
        "media_bpm": [
            "74",
            "88",
            "93",
            "86",
            "104",
            "96",
            "87",
            "75",
            "120",
            "100",
            "90",
            "70",
            "110",
        ],
    },
    {
        "title": "Narcose – Panda Eyes",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "10,840",
        "comments_count": "18",
        "url": "https://ektoplazm.com/free-music/narcose-panda-eyes",
        "img": "https://ektoplazm.com/img/narcose-panda-eyes-300x292.jpg",
        "tracks": [
            "Gathering Clouds",
            "Gonzos Last Ride",
            "Smoke Signals",
            "Panda Eyes",
            "Inuit",
            "The Shores Of The Idaho",
            "Nighthawk",
            "Floating Through Space",
        ],
        "media_bpm": ["75", "90", "73", "70", "80", "105", "100", "85"],
    },
    {
        "title": "Supersillyus – Charade",
        "styles": ["Downtempo", "Psy Dub", "Psybreaks"],
        "download_count": "19,663",
        "comments_count": "26",
        "url": "https://ektoplazm.com/free-music/supersillyus-charade",
        "img": "https://ektoplazm.com/img/supersillyus-charade-300x300.jpg",
        "tracks": [
            "Mirage a Trois",
            "Aeon Bahamut",
            "Trancendental Meditation",
            "A List Of Instructions For When I'm Human",
            "The Great Shenanigan",
            "Charade",
        ],
        "media_bpm": [
            "90",
            "172",
            "100",
            "7",
            "4",
            "4",
            "4",
            "3",
            "4",
            "115",
            "123",
            "125",
            "123",
            "10",
            "4",
        ],
    },
    {
        "title": "Numatica – Cascade",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "9,911",
        "comments_count": "9",
        "url": "https://ektoplazm.com/free-music/numatica-cascade",
        "img": "https://ektoplazm.com/img/numatica-cascade-300x300.jpg",
        "tracks": [
            "Tired Eyes (feat. Ones & Zeros)",
            "Caravan Of Dub",
            "Sunday Tea",
            "Dirty Little Bird",
        ],
        "media_bpm": ["126", "98", "123", "130"],
    },
    {
        "title": "Sixis & Expedizion – Awakening World Remixes",
        "styles": ["Downtempo", "Glitch", "Psy Dub"],
        "download_count": "9,508",
        "comments_count": "7",
        "url": "https://ektoplazm.com/free-music/sixis-expedizion-awakening-world-remixes",
        "img": "https://ektoplazm.com/img/sixis-and-expedizion-awakening-world-remixes-300x300.jpg",
        "tracks": [
            "Awakening World",
            "Awakening World",
            "Awakening World",
            "Awakening World",
            "Awakening World",
            "Awakening World",
        ],
        "media_bpm": ["85", "85", "80", "85", "100", "85"],
    },
    {
        "title": "Dub Warriors Vol. 2",
        "styles": ["Bass Music", "Downtempo", "Psy Dub"],
        "download_count": "16,728",
        "comments_count": "7",
        "url": "https://ektoplazm.com/free-music/dub-warriors-vol-2",
        "img": "https://ektoplazm.com/img/va-dub-warriors-vol-2-300x300.jpg",
        "tracks": [
            "A Fonder View",
            "Untitled",
            "Incantations",
            "To Be With You",
            "Sir Rabbit Tuft",
            "Listen To The Deepness",
            "Ennead",
            "Kindred",
            "Before",
            "HomeRoots",
            "Change",
            "Amatlan Of Quetzalcoatl",
        ],
        "media_bpm": [
            "140",
            "120",
            "140",
            "116",
            "120",
            "118",
            "154",
            "135",
            "86",
            "90",
            "134",
            "85",
        ],
    },
    {
        "title": "Tara Putra vs Psychoz – Shanti",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "10,430",
        "comments_count": "12",
        "url": "https://ektoplazm.com/free-music/tara-putra-vs-psychoz-shanti",
        "img": "https://ektoplazm.com/img/tara-putra-vs-psychoz-shanti-300x300.jpg",
        "tracks": [
            "Paradise",
            "Happiness",
            "Euro Bongs",
            "Point of View",
            "Sigambry Curry",
            "Shanti",
            "Channel Dub Sumatra",
            "Phazedub",
            "Subdubtion",
        ],
        "media_bpm": ["83", "90", "66", "80", "76", "80", "80", "80", "60"],
    },
    {
        "title": "False Identity – The Pond Where I Belong",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "9,016",
        "comments_count": "18",
        "url": "https://ektoplazm.com/free-music/false-identity-the-pond-where-i-belong",
        "img": "https://ektoplazm.com/img/false-identity-the-pond-where-i-belong-300x277.jpg",
        "tracks": [
            "The Odious (T)Ode",
            "Fumigation Fluctuation",
            "Contentment",
            "Charming Marbles",
            "Gnome More Fishing Trips",
            "Kissing The Joy As It Flies",
            "Meanderings Of A Gnome",
            "Pond Where I Belong",
        ],
        "media_bpm": ["73", "94", "85", "88", "92", "76", "80", "67"],
    },
    {
        "title": "Smörgåsbord Vol. 2: Psiarrhea",
        "styles": ["Deep Trance", "Downtempo", "Psy Dub"],
        "download_count": "18,301",
        "comments_count": "20",
        "url": "https://ektoplazm.com/free-music/smorgasbord-vol-2-psiarrhea",
        "img": "https://ektoplazm.com/img/va-smorgasbord-vol-2-psiarrhea-300x300.jpg",
        "tracks": [
            "Harmonic Junkie",
            "Bonzai",
            "The Midnight Harvest",
            "Endless",
            "Through The Ard",
            "Moor",
            "Cowboys And Co-Pilots",
            "Songs To The Self",
            "Subterranean Bounce",
            "Drop",
            "Deep Sea Dubbin'",
        ],
        "media_bpm": [
            "108",
            "126",
            "110",
            "82",
            "100",
            "71",
            "125",
            "89",
            "72",
            "110",
            "70",
        ],
    },
    {
        "title": "Shamanizm Parallelii – Tales From Colored Tepee",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "15,854",
        "comments_count": "25",
        "url": "https://ektoplazm.com/free-music/shamanizm-parallelii-tales-from-colored-tepee",
        "img": "https://ektoplazm.com/img/shamanizm-parallelii-tales-from-colored-tepee-300x295.jpg",
        "tracks": [
            "Autumn Kailash",
            "The Earth In Your Hands",
            "Temple Of Buddha High In Sky",
            "Mountain’s Snow",
            "Heartbeat Of Asian Spirit",
            "Parallelia",
            "Purple Sky",
            "Space Butterfly",
            "Spaceship In My Brain",
            "The Thousand And The Second Night",
            "Tales From Colored Tepee",
        ],
        "media_bpm": ["105", "120", "95", "110", "73", "90", "70", "130", "120", "130"],
    },
    {
        "title": "Soulacybin – Gratitude",
        "styles": ["Downtempo", "Glitch", "Psy Dub"],
        "download_count": "15,064",
        "comments_count": "6",
        "url": "https://ektoplazm.com/free-music/soulacybin-gratitude",
        "img": "https://ektoplazm.com/img/soulacybin-gratitude-300x300.jpg",
        "tracks": [
            "The Activation Part 1",
            "Moldavisions",
            "Sundari",
            "Mycophagous",
            "Alien Life",
            "Synchromystic",
            "The Activation Part 2",
        ],
        "media_bpm": ["82", "75", "80", "70", "100", "85", "97"],
    },
    {
        "title": "Floating Planet – Fractal Wortex",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "9,173",
        "comments_count": "19",
        "url": "https://ektoplazm.com/free-music/floating-planet-fractal-wortex",
        "img": "https://ektoplazm.com/img/floating-planet-fractal-wortex-300x300.jpg",
        "tracks": [
            "Fractal Wortex",
            "Quirk",
            "Rainforest",
            "Awakening The Divine Within (Part 1)",
            "Awakening The Divine Within (Part 2)",
        ],
        "media_bpm": ["120", "90", "98", "108", "108"],
    },
    {
        "title": "Tara Putra – Driven By Dub",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "13,318",
        "comments_count": "12",
        "url": "https://ektoplazm.com/free-music/tara-putra-driven-by-dub",
        "img": "https://ektoplazm.com/img/tara-putra-driven-by-dub-300x300.jpg",
        "tracks": [
            "Universal Bubble",
            "Awka",
            "Tight Flair",
            "Dubland Mountains",
            "Find A Way",
            "Euro Bongs",
            "Dubland Mountains",
            "Dubland Mountains",
            "Karoshi Dub",
            "Find A Way",
        ],
        "media_bpm": ["70", "135", "80", "70", "60", "66", "70", "70", "85", "60"],
    },
    {
        "title": "Flowertz – Kumbhaka",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "17,730",
        "comments_count": "39",
        "url": "https://ektoplazm.com/free-music/flowertz-kumbhaka",
        "img": "https://ektoplazm.com/img/flowertz-kumbhaka-300x300.jpg",
        "tracks": [
            "Mystical Call",
            "World Confusion",
            "Ekadasi Days",
            "Little Universe",
            "Cosmic Love",
            "Dub It Up",
            "Lotus Dub",
            "What We Think We Become",
            "Kumbhaka",
            "Morning Smile",
            "Ancient Future",
        ],
        "media_bpm": [
            "90",
            "90",
            "90",
            "110",
            "100",
            "91",
            "105",
            "110",
            "100",
            "110",
            "90",
        ],
    },
    {
        "title": "Flux Vortex – Lunar Web",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "7,020",
        "comments_count": "10",
        "url": "https://ektoplazm.com/free-music/flux-vortex-lunar-web",
        "img": "https://ektoplazm.com/img/flux-vortex-lunar-web-300x300.jpg",
        "tracks": ["Hologram", "Squelch", "HAL9000", "Her Tongue Is Like A Jellyfish"],
        "media_bpm": ["92", "98", "90", "89", "90"],
    },
    {
        "title": "Expedizion – Defragmentation",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "8,541",
        "comments_count": "7",
        "url": "https://ektoplazm.com/free-music/expedizion-defragmentation",
        "img": "https://ektoplazm.com/img/expedizion-defragmentation-300x300.jpg",
        "tracks": [
            "Fragmented Dreams (Part 1 Germination)",
            "Cyclic Time",
            "Rooted In Love",
            "Fragmented Dreams (Part 2 Growth)",
            "Fragmented Dreams (Part 3 Blossoming)",
        ],
        "media_bpm": ["104", "160", "85", "104", "104"],
    },
    {
        "title": "Bloop – Azure Essence",
        "styles": ["Downtempo", "Glitch", "Psy Dub"],
        "download_count": "7,725",
        "comments_count": "4",
        "url": "https://ektoplazm.com/free-music/bloop-azure-essence",
        "img": "https://ektoplazm.com/img/bloop-azure-essence-300x300.jpg",
        "tracks": [
            "A Shift In Perspective",
            "Ocean Jasper",
            "Dryspell",
            "Azure Essence",
            "Ocean Jasper",
        ],
        "media_bpm": ["140", "140", "140", "160", "140"],
    },
    {
        "title": "Rukirek – Hollow Void",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "9,316",
        "comments_count": "17",
        "url": "https://ektoplazm.com/free-music/rukirek-hollow-void",
        "img": "https://ektoplazm.com/img/rukirek-hollow-void-300x300.jpg",
        "tracks": [
            "Hollow Void",
            "Last Step Before The Crash Of It All... And Go Again",
            "Heat Haze",
        ],
        "media_bpm": ["110", "85", "80"],
    },
    {
        "title": "Therange Freak In Dub – Cosmic Transformation",
        "styles": ["Downtempo", "Psy Dub", "Swamp"],
        "download_count": "9,435",
        "comments_count": "7",
        "url": "https://ektoplazm.com/free-music/therange-freak-in-dub-cosmic-transformation",
        "img": "https://ektoplazm.com/img/therange-freak-in-dub-cosmic-transformation-300x300.jpg",
        "tracks": ["Intro", "Psychic Vivisection 2", "Irminsul", "Outro"],
        "media_bpm": ["130", "130", "130", "130"],
    },
    {
        "title": "UCHU – Information",
        "styles": ["Deep Trance", "Downtempo", "Psy Dub"],
        "download_count": "14,656",
        "comments_count": "12",
        "url": "https://ektoplazm.com/free-music/uchu-information",
        "img": "https://ektoplazm.com/img/uchu-information-300x300.jpg",
        "tracks": [
            "Information",
            "Gnome Attack",
            "Fat Cat",
            "Gorilla Fart",
            "Montjuic (Album Version)",
        ],
        "media_bpm": ["100", "100", "90", "100", "116"],
    },
    {
        "title": "Ethneomystica Vol. 3",
        "styles": ["Downtempo", "Psy Dub", "Psybreaks"],
        "download_count": "24,860",
        "comments_count": "27",
        "url": "https://ektoplazm.com/free-music/ethneomystica-vol-3",
        "img": "https://ektoplazm.com/img/va-entheomystica-vol-3.jpg",
        "tracks": [
            "Kunilingus",
            "Colonization",
            "Air Force None",
            "Strawberry Lassy",
            "The Holidayer",
            "Kaleidoscope",
            "Pequenisky",
            "La Muerte Peluda",
            "Spiritual Beings",
            "Nystart",
            "The Crowd",
        ],
        "media_bpm": [
            "130",
            "120",
            "135",
            "128",
            "130",
            "95",
            "70",
            "78",
            "85",
            "114",
            "120",
        ],
    },
    {
        "title": "Smörgåsbord",
        "styles": ["Deep Trance", "Downtempo", "Psy Dub"],
        "download_count": "22,822",
        "comments_count": "37",
        "url": "https://ektoplazm.com/free-music/smorgasbord",
        "img": "https://ektoplazm.com/img/va-smorgasbord-300x300.jpg",
        "tracks": [
            "Playing For Rain",
            "Derive And Detach",
            "Everything Is Awesome",
            "Drinking Cornish Clouds",
            "The Capital",
            "Fiddle Sticks",
            "My Cat Is A Dragon",
            "Salamander",
            "Enigmagician",
            "Nama",
            "Flower Sun",
        ],
        "media_bpm": [
            "101",
            "85",
            "65",
            "105",
            "96",
            "100",
            "108",
            "128",
            "137",
            "77",
            "99",
            "128",
            "75",
        ],
    },
    {
        "title": "Dubz Cooker – Zero Zero",
        "styles": ["Downtempo", "Glitch", "Psy Dub"],
        "download_count": "8,738",
        "comments_count": "14",
        "url": "https://ektoplazm.com/free-music/dubz-cooker-zero-zero",
        "img": "https://ektoplazm.com/img/dubz-cooker-zero-zero-300x300.jpg",
        "tracks": [
            "Dub Ritual",
            "Self Control",
            "Homo Sapiens",
            "Pscientist",
            "Rise Up",
        ],
        "media_bpm": ["120", "120", "120", "126", "120"],
    },
    {
        "title": "Jeremy’s Aura – Being And Becoming…",
        "styles": ["Deep Trance", "Downtempo", "Psy Dub"],
        "download_count": "16,733",
        "comments_count": "10",
        "url": "https://ektoplazm.com/free-music/jeremys-aura-being-and-becoming",
        "img": "https://ektoplazm.com/img/jeremys-aura-being-and-becoming-300x300.jpg",
        "tracks": [
            "Kepulangan",
            "Roots In A Lattice",
            "Satire Of The Sleuth",
            "Superhero Island",
            "Pineal Gamelan",
            "Reincorporate",
            "Being And Becoming...",
        ],
        "media_bpm": [
            "100",
            "105",
            "100",
            "85",
            "140",
            "120",
            "100",
            "75",
            "98",
            "65",
            "70",
            "75",
            "75",
            "80",
            "90",
            "125",
            "80",
        ],
    },
    {
        "title": "False Identity – Community Of Me",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "7,050",
        "comments_count": "9",
        "url": "https://ektoplazm.com/free-music/false-identity-community-of-me",
        "img": "https://ektoplazm.com/img/false-identity-community-of-me.jpg",
        "tracks": [
            "The Perpetual Wandering Of The Ly-Cilph",
            "Intersection Dimension",
            "Every Branch Must Bend",
        ],
        "media_bpm": ["95", "90", "83"],
    },
    {
        "title": "Sacral Fractal",
        "styles": ["Ambient", "Downtempo", "Psy Dub"],
        "download_count": "17,043",
        "comments_count": "24",
        "url": "https://ektoplazm.com/free-music/sacral-fractal",
        "img": "https://ektoplazm.com/img/va-sacral-fractal-300x300.jpg",
        "tracks": [
            "Zen Attitude",
            "Aerial Roots",
            "Follow The Music",
            "Silenced Journeys",
            "Fallen Leaf Lake",
            "Sunspots",
            "Reborn",
            "Moonwrapper",
            "Rysselblower",
            "The Tree",
            "Gooseberry",
            "Danza De Amor",
            "This Day",
            "Ascending To The Heaven",
            "Room",
            "Undergrowth",
            "High On Mountain",
        ],
        "media_bpm": [
            "0",
            "72",
            "70",
            "103",
            "136",
            "90",
            "74",
            "138",
            "80",
            "106",
            "90",
            "120",
            "120",
            "100",
            "77",
            "142",
            "0",
        ],
    },
    {
        "title": "Dreadlock Tales – Gravity Equals Love Remixer",
        "styles": ["Downtempo", "Psy Dub", "Techno"],
        "download_count": "11,128",
        "comments_count": "5",
        "url": "https://ektoplazm.com/free-music/dreadlock-tales-gravity-equals-love-remixer",
        "img": "https://ektoplazm.com/img/dreadlock-tales-gravity-equals-love-remixer-300x300.jpg",
        "tracks": [
            "Gravity Equals Love",
            "Gravity Equals Love",
            "Gravity Equals Love",
            "Gravity Equals Love",
        ],
        "media_bpm": ["87", "130", "130", "130"],
    },
    {
        "title": "Shamanizm Parallelii – The World In A Drop Of Rain",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "9,945",
        "comments_count": "17",
        "url": "https://ektoplazm.com/free-music/shamanizm-parallelii-the-world-in-a-drop-of-rain",
        "img": "https://ektoplazm.com/img/shamanizm-parallelii-the-world-in-a-drop-of-rain-300x300.jpg",
        "tracks": [
            "Box With Old Toys",
            "Place Where Ganga Was Born",
            "United Spirit",
            "Shadows Of The Mountain's Shamans",
            "Space Sweet Home",
            "Three G",
            "The World In A Drop Of Rain",
            "Erinaceus Europaeus In The Mist",
        ],
        "media_bpm": ["130", "140", "120", "146", "120", "120", "92"],
    },
    {
        "title": "E.R.S. – Rebelized",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "11,599",
        "comments_count": "11",
        "url": "https://ektoplazm.com/free-music/e-r-s-rebelized",
        "img": "https://ektoplazm.com/img/ers-rebelized-300x300.jpg",
        "tracks": [
            "Iriedelic Part 1",
            "Iriedelic Part 2",
            "Visions Of Dong",
            "The Bongdub",
            "Our Speciality",
            "We Are Rising",
        ],
        "media_bpm": ["92", "92", "67", "5", "98", "89", "65"],
    },
    {
        "title": "Kaminanda – Ancestors & Guardians",
        "styles": ["Downtempo", "Glitch", "Psy Dub"],
        "download_count": "18,312",
        "comments_count": "21",
        "url": "https://ektoplazm.com/free-music/kaminanda-ancestors-guardians",
        "img": "https://ektoplazm.com/img/kaminanda-ancestors-and-guardians-300x300.jpg",
        "tracks": [
            "Alchemy Resonance",
            "The Portal",
            "Panther Dreams",
            "Moonlight Tango",
            "Liberation",
            "Time Travellers",
            "Liquid Sunrise",
            "Sadhu",
            "Optimal Trajectstasy",
            "Guardians Of Virtue",
            "The Great Alignment",
        ],
        "media_bpm": [
            "88",
            "107",
            "100",
            "100",
            "97",
            "97",
            "85",
            "85",
            "83",
            "78",
            "0",
        ],
    },
    {
        "title": "Globular – Digging & Building",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "12,793",
        "comments_count": "23",
        "url": "https://ektoplazm.com/free-music/globular-digging-building",
        "img": "https://ektoplazm.com/img/globular-digging-and-building.jpg",
        "tracks": ["Deeper Than Dirt", "Infinity Inside"],
        "media_bpm": ["71", "80"],
    },
    {
        "title": "Narcose – The Dreams Of Zoroaster",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "10,764",
        "comments_count": "22",
        "url": "https://ektoplazm.com/free-music/narcose-the-dreams-of-zoroaster",
        "img": "https://ektoplazm.com/img/narcose-the-dreams-of-zoroaster-300x300.jpg",
        "tracks": [
            "Atmikha",
            "The Road To Humahuaca",
            "Icarus",
            "The Rings Of Saturn",
            "Landing On Helike",
        ],
        "media_bpm": ["90", "105", "90", "135", "100"],
    },
    {
        "title": "Ethneomystica Vol. 1",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "25,620",
        "comments_count": "24",
        "url": "https://ektoplazm.com/free-music/ethneomystica-vol-1",
        "img": "https://ektoplazm.com/img/va-ethneomystica-vol-1.jpg",
        "tracks": [
            "Sub Aqua",
            "Swinging Satori",
            "Black Hole To The Soul",
            "Damien El Racho",
            "Infinity Inside",
            "The Wanderer",
            "Shamanic Wisdom",
            "Faces Come Out Of The Rain",
            "Pink Glasses",
            "Riddlefish",
        ],
        "media_bpm": ["95", "80", "110", "70", "80", "80", "82", "70", "120", "85"],
    },
    {
        "title": "Bioscape – Living Connection",
        "styles": ["Ambient", "Downtempo", "Psy Dub"],
        "download_count": "18,625",
        "comments_count": "34",
        "url": "https://ektoplazm.com/free-music/bioscape-living-connection",
        "img": "https://ektoplazm.com/img/bioscape-living-connection-300x300.jpg",
        "tracks": [
            "Mountaintop Meditation",
            "Shaolin Cosmos",
            "Not All Who Wander Are Lost",
            "Underwater Bliss",
            "Explore The Night",
            "Biological Harmonies",
            "Everyday Places & Natural Spaces",
            "Amphibian Dreams",
            "Nature Essence",
            "Storm Comfort",
            "Creation Dub",
            "Living Connection",
        ],
        "media_bpm": [
            "66",
            "60",
            "95",
            "75",
            "90",
            "90",
            "75",
            "90",
            "80",
            "80",
            "72",
            "75",
        ],
    },
    {
        "title": "Yestegan chaY – Shikoon",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "8,476",
        "comments_count": "28",
        "url": "https://ektoplazm.com/free-music/yestegan-chay-shikoon",
        "img": "https://ektoplazm.com/img/yestegan-chay-shikoon-300x300.jpg",
        "tracks": [
            "Yeh Estekan Chaee",
            "ElectroEthnica",
            "Aiwa Alek",
            "Ballaboochang",
            "Abulele",
        ],
        "media_bpm": ["120", "90", "100", "100", "130", "5", "4"],
    },
    {
        "title": "DJ Basilisk – The Colours of Ektoplazm",
        "styles": ["Deep Trance", "Downtempo", "Glitch", "Psy Dub", "Psybreaks"],
        "download_count": "50,555",
        "comments_count": "65",
        "url": "https://ektoplazm.com/free-music/dj-basilisk-the-colours-of-ektoplazm",
        "img": "https://ektoplazm.com/img/dj-basilisk-the-colours-of-ektoplazm-300x300.jpg",
        "tracks": [],
        "media_bpm": [],
    },
    {
        "title": "Mind Gap",
        "styles": ["Downtempo", "Glitch", "Psy Dub"],
        "download_count": "14,447",
        "comments_count": "27",
        "url": "https://ektoplazm.com/free-music/mind-gap",
        "img": "https://ektoplazm.com/img/va-mind-gap.jpg",
        "tracks": [
            "El Cadub",
            "Digil Sippy",
            "Peace",
            "Fun G",
            "Bermuda Triangle",
            "All You Got",
            "Classification",
            "D Temp",
            "Dream Forever",
            "Der Dritte Raum",
        ],
        "media_bpm": ["70", "100", "100", "105", "84", "70", "100", "90", "110", "100"],
    },
    {
        "title": "Supersillyus – Interabang",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "18,007",
        "comments_count": "25",
        "url": "https://ektoplazm.com/free-music/supersillyus-interabang",
        "img": "https://ektoplazm.com/img/supersillyus-interabang-300x300.jpg",
        "tracks": [
            "Palindromeda",
            "Collide-O-Scope",
            "Interabang",
            "The Silly Revolution",
            "Bananotechnology (Surface)",
        ],
        "media_bpm": ["77", "150", "80", "105", "140", "70", "93", "186"],
    },
    {
        "title": "Globular – Magnitudes Of Order",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "23,235",
        "comments_count": "64",
        "url": "https://ektoplazm.com/free-music/globular-magnitudes-of-order",
        "img": "https://ektoplazm.com/img/globular-magnitudes-of-order.jpg",
        "tracks": [
            "Synchronicity City 3.0",
            "Monkey Fluster",
            "Fire & Stars",
            "Up The Xylem Elevator",
            "Gateways",
            "PLANCK!",
            "Concinnity & Chaos",
            "Dance Of The Logarithm",
        ],
        "media_bpm": ["77", "95", "75", "77", "86", "98", "83", "73"],
    },
    {
        "title": "Kataphasis – Earth Magick",
        "styles": ["Downtempo", "Organic", "Psy Dub"],
        "download_count": "19,938",
        "comments_count": "28",
        "url": "https://ektoplazm.com/free-music/kataphasis-earth-magick",
        "img": "https://ektoplazm.com/img/kataphasis-earth-magick1-300x300.jpg",
        "tracks": [
            "I Won't Leave You Behind",
            "Wandering",
            "Sweeping Leaves On A Windy Day",
            "Reprieve",
            "Meraki",
            "Reconciliation",
            "Hashish And Mulberry",
            "I Won't Leave You Behind",
            "Prophesy",
            "Wandering",
            "Sweeping Leaves",
            "Reprieve",
            "Hashish And Mulberry",
            "Sweeping Leaves",
            "Wandering",
            "Sweeping Leaves",
            "I Won't Leave You Behind",
        ],
        "media_bpm": [
            "135",
            "92",
            "78",
            "114",
            "54",
            "60",
            "144",
            "160",
            "135",
            "100",
            "92",
            "156",
            "120",
            "160",
            "156",
            "160",
            "78",
            "85",
        ],
    },
    {
        "title": "HuuHaa – HaaHuu 2012",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "10,382",
        "comments_count": "13",
        "url": "https://ektoplazm.com/free-music/huuhaa-haahuu-2012",
        "img": "https://ektoplazm.com/img/huuhaa-haahuu-2012-300x300.jpg",
        "tracks": ["HaaHuu", "Mayan Mar", "JoikHaa", "5D", "HuuHaa"],
        "media_bpm": ["100", "80", "135", "130", "100"],
    },
    {
        "title": "Psilogod – Exquisite Landscapes",
        "styles": ["Bass Music", "Psy Dub"],
        "download_count": "11,881",
        "comments_count": "21",
        "url": "https://ektoplazm.com/free-music/psilogod-exquisite-landscapes",
        "img": "https://ektoplazm.com/img/psilogod-exquisite-landscapes-300x300.jpg",
        "tracks": [
            "The Second Gate",
            "Digital Demons",
            "Exquisite Landscapes",
            "My Pet Insect",
            "The Serpent",
            "Space Dip",
            "Witch Doctor",
            "Please Stop The Violence",
            "Vega Signal",
            "God As A Source",
            "Hope In Blue",
            "Synthesonata",
            "Edge Of The World",
            "Within Time",
        ],
        "media_bpm": [
            "100",
            "70",
            "75",
            "72",
            "5",
            "77",
            "5",
            "77",
            "5",
            "72",
            "5",
            "72",
            "5",
            "72",
            "5",
            "72",
            "5",
            "110",
            "102",
            "100",
            "60",
        ],
    },
    {
        "title": "Radioactive Sandwich & Globular – Sorbet For The Soul",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "21,620",
        "comments_count": "45",
        "url": "https://ektoplazm.com/free-music/radioactive-sandwich-globular-sorbet-for-the-soul",
        "img": "https://ektoplazm.com/img/radioactive-sandwich-and-globular-sorbet-for-the-soul-300x300.jpg",
        "tracks": ["Lemon", "Lengo", "Mango", "Mamon"],
        "media_bpm": ["97", "97", "95", "91"],
    },
    {
        "title": "Shantifax – Complete Tranceformation",
        "styles": ["Downtempo", "Progressive", "Psy Dub"],
        "download_count": "19,870",
        "comments_count": "21",
        "url": "https://ektoplazm.com/free-music/shantifax-complete-tranceformation",
        "img": "https://ektoplazm.com/img/shantifax-complete-tranceformation-300x300.jpg",
        "tracks": [
            "Awake",
            "Aum",
            "Concrete Combination",
            "Amygdala on diamonds",
            "Rudra",
            "Stone Steps",
            "Karma Never Forgets",
            "Be Human",
            "The Same",
            "Northern Lights",
        ],
        "media_bpm": [
            "120",
            "90",
            "100",
            "130",
            "138",
            "124",
            "102",
            "120",
            "104",
            "140",
        ],
    },
    {
        "title": "Dub Warriors Vol. 1",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "21,399",
        "comments_count": "27",
        "url": "https://ektoplazm.com/free-music/dub-warriors-vol-1",
        "img": "https://ektoplazm.com/img/va-dub-warriors-vol-1-300x300.jpg",
        "tracks": [
            "Subminimal Message",
            "Off The Grid",
            "De-pressurize",
            "Seeking That Place",
            "Coping With Babylon",
            "Down Where The Fishes Glow",
            "Trojan Hyper Dub",
        ],
        "media_bpm": ["135", "140", "101", "137", "144", "130", "135"],
    },
    {
        "title": "Kaminanda – Gateways Of Consciousness",
        "styles": ["Deep Trance", "Downtempo", "Psy Dub"],
        "download_count": "40,279",
        "comments_count": "48",
        "url": "https://ektoplazm.com/free-music/kaminanda-gateways-of-consciousness",
        "img": "https://ektoplazm.com/img/kaminanda-gateways-of-consciousness-300x300.jpg",
        "tracks": [
            "Yessence",
            "Conscious Droplets",
            "The Yum Factor",
            "Ritual Ecologies",
            "Fearless Bridger",
            "Temple Of De'Light",
            "S'elf Power",
            "Subterranean Fountain",
            "Pele's Breath",
            "Peace Mala",
            "As Above So Below",
        ],
        "media_bpm": [
            "89",
            "90",
            "97",
            "105",
            "110",
            "110",
            "110",
            "100",
            "85",
            "108",
            "68",
        ],
    },
    {
        "title": "Full Circle",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "9,348",
        "comments_count": "6",
        "url": "https://ektoplazm.com/free-music/full-circle",
        "img": "https://ektoplazm.com/img/va-full-circle-300x300.jpg",
        "tracks": ["Submerged", "Bloody Dub", "UFO", "Hylozoism", "Into The Water"],
        "media_bpm": ["84", "140", "85", "134", "130"],
    },
    {
        "title": "Integer – Ventilation",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "9,611",
        "comments_count": "11",
        "url": "https://ektoplazm.com/free-music/integer-ventilation",
        "img": "https://ektoplazm.com/img/integer-ventilation-300x300.jpg",
        "tracks": [
            "Ventilation",
            "Gurgle Dub",
            "Knife & Spoon Dub",
            "South & West",
            "Ventilation",
        ],
        "media_bpm": ["100", "140", "112", "0", "85"],
    },
    {
        "title": "Radioactive Sandwich – Mirage",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "24,969",
        "comments_count": "53",
        "url": "https://ektoplazm.com/free-music/radioactive-sandwich-mirage",
        "img": "https://ektoplazm.com/img/radioactive-sandwich-mirage-300x300.jpg",
        "tracks": [
            "Into The Desert",
            "A Broken Reality",
            "An Echo Is The Shadow Of A Sound",
            "Sullen Choirboy",
            "Sigogglin",
            "Time Dilation",
            "Bhagwan",
        ],
        "media_bpm": ["65", "65", "100", "70", "95", "105", "70"],
    },
    {
        "title": "Tara Putra – In Dubland",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "30,887",
        "comments_count": "39",
        "url": "https://ektoplazm.com/free-music/tara-putra-in-dubland",
        "img": "https://ektoplazm.com/img/tara-putra-in-dubland-300x300.jpg",
        "tracks": [
            "Affeninsel",
            "Channel Dub Sumatra",
            "Dubland Coastline",
            "A Dubbers Galore",
            "Freedom Fighters",
            "This Is My Prayer",
            "Interplanetary Dub Express",
            "Dubland Mountains",
            "Dubland Mountains",
            "Dubland Mountains",
            "Dubland Mountains",
        ],
        "media_bpm": [
            "72",
            "80",
            "90",
            "84",
            "82",
            "120",
            "71",
            "70",
            "70",
            "80",
            "70",
        ],
    },
    {
        "title": "Supersillyus – Tesselations",
        "styles": ["Downtempo", "Psy Dub", "Psybreaks"],
        "download_count": "15,594",
        "comments_count": "25",
        "url": "https://ektoplazm.com/free-music/supersillyus-tesselations",
        "img": "https://ektoplazm.com/img/supersillyus-tesselations-300x287.jpg",
        "tracks": [
            "Unmentioned Dimensions",
            "3 Sphere",
            "Demicube",
            "54M8471M3",
            "Dekeract",
            "Zoopanatural Boogaloo",
            "Conga Lineage",
            "Tesselations",
            "Polyhedral Heathen",
            "Neblasta",
            "Affinity For Infinity",
            "Deemdreems And Tippytaps",
            "Particle-Beam-Handshakes",
            "Bury The Bat. Goodnight Pratt",
        ],
        "media_bpm": [
            "107",
            "107",
            "120",
            "120",
            "100",
            "120",
            "120",
            "120",
            "120",
            "131",
            "160",
            "150",
            "80",
            "160",
            "90",
            "180",
            "90",
            "180",
            "90",
            "180",
            "90",
            "180",
        ],
    },
    {
        "title": "Soulacybin – Self-Existing Earth",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "20,901",
        "comments_count": "36",
        "url": "https://ektoplazm.com/free-music/soulacybin-self-existing-earth",
        "img": "https://ektoplazm.com/img/soulacybin-self-existing-earth-300x300.jpg",
        "tracks": [
            "Mindful Levitation",
            "Word, Sound And Power",
            "Youthman Dub",
            "Bolzar",
            "Soldier Of Dub",
            "Hunab Ku",
            "Azurescence",
            "Dreamscape",
            "Blessings Manifest",
        ],
        "media_bpm": ["70", "74", "88", "83", "92", "73", "90", "97", "100"],
    },
    {
        "title": "Globular – A Self-Fulfilling Prophecy",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "36,376",
        "comments_count": "84",
        "url": "https://ektoplazm.com/free-music/globular-a-self-fulfilling-prophecy",
        "img": "https://ektoplazm.com/img/globular-a-self-fulfilling-prophecy-300x300.jpg",
        "tracks": [
            "Feeding Back Forwards",
            "A Singular Synergy",
            "Subversion",
            "This, Here, Now",
            "The Loon",
            "A Highly Sprung Spring",
            "To The Other Side Of Fractal Phase Space",
            "From Mind, There Spills Forth Light",
        ],
        "media_bpm": ["79", "76", "80", "99", "73", "103", "83", "70"],
    },
    {
        "title": "Shantifax – Delete Automation",
        "styles": ["Downtempo", "Progressive", "Psy Dub"],
        "download_count": "18,392",
        "comments_count": "25",
        "url": "https://ektoplazm.com/free-music/shantifax-delete-automation",
        "img": "https://ektoplazm.com/img/shantifax-delete-automation-300x300.jpg",
        "tracks": [
            "Formatio Reticularis",
            "Hushushush",
            "One Thing",
            "Ancient Fields",
            "Desert Trip",
            "Aquarius",
            "Grau N",
            "Out Is In",
        ],
        "media_bpm": ["122", "85", "95", "118", "120", "138", "137", "90"],
    },
    {
        "title": "Globular – In Formation",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "16,223",
        "comments_count": "24",
        "url": "https://ektoplazm.com/free-music/globular-in-formation",
        "img": "https://ektoplazm.com/img/globular-in-formation-300x295.jpg",
        "tracks": [
            "Paranormaloid",
            "Fractalicious Fantastifications",
            "Nahajai",
            "Dimension Extension",
            "The Missing Quanta",
        ],
        "media_bpm": ["100", "100", "111", "85", "91"],
    },
    {
        "title": "The Return Of Quetzalcoatl",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "14,502",
        "comments_count": "23",
        "url": "https://ektoplazm.com/free-music/the-return-of-quetzalcoatl",
        "img": "https://ektoplazm.com/img/va-the-return-of-quetzalcoatl-300x300.jpg",
        "tracks": [
            "Walking In The Desert",
            "Organic Structures",
            "The Mystical Quest",
            "Frogspawn",
            "Mystic Forest",
            "Dreamwards Again",
            "Mutant",
            "Spring Is Over",
            "Flex",
        ],
        "media_bpm": ["100", "80", "70", "120", "120", "110", "120", "120", "140"],
    },
    {
        "title": "Hinkstep – Sunrise From The Treetops",
        "styles": ["Downtempo", "Experimental", "Psy Dub"],
        "download_count": "34,140",
        "comments_count": "92",
        "url": "https://ektoplazm.com/free-music/hinkstep-sunrise-from-the-treetops",
        "img": "https://ektoplazm.com/img/hinkstep-sunrise-from-the-treetops-300x300.jpg",
        "tracks": [
            "Sunrise From The Treetops",
            "Moonwalk On Mushroom Street",
            "Dreamland Dub",
            "Medusa",
            "Aldrig Mer",
            "So Beautiful So Strange",
            "Sleep Again",
        ],
        "media_bpm": [
            "126",
            "9",
            "4",
            "80",
            "120",
            "6",
            "4",
            "67",
            "2",
            "130",
            "6",
            "4",
            "75",
            "120",
        ],
    },
    {
        "title": "Psyderchill",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "18,307",
        "comments_count": "17",
        "url": "https://ektoplazm.com/free-music/psyderchill",
        "img": "https://ektoplazm.com/img/va-psyderchill-300x300.jpg",
        "tracks": [
            "Realms Of Jupiter",
            "Folding Strings",
            "Visitors Of Gaia",
            "A Deep Breath",
            "Soulfly",
            "Like We Know",
            "Eostrae",
            "Endless",
            "Life",
            "Bipolar Eclipse",
            "Chilling Plastics",
        ],
        "media_bpm": [
            "102",
            "104",
            "73",
            "87",
            "104",
            "110",
            "66",
            "90",
            "95",
            "120",
            "92",
        ],
    },
    {
        "title": "Space Forming Vol. 3",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "20,950",
        "comments_count": "29",
        "url": "https://ektoplazm.com/free-music/space-forming-vol-3",
        "img": "https://ektoplazm.com/img/va-space-forming-vol-3-300x300.jpg",
        "tracks": [
            "Squids And Rainbows",
            "Gabys Lullaby",
            "Wake Up!",
            "Merciful Damage",
            "Lesdub",
            "Petrichor",
            "Gåte",
            "Spirit World",
            "Atmosphere",
            "C-Happy",
            "Smooth Turbulence",
            "Nowhere Inside Out",
            "Mushi",
            "Amanita",
            "Breakin A Bad Code",
            "Purple Lake",
            "Mystery",
            "Vida Espiritual",
            "Janet",
            "The Lost Empire",
            "Desert Dreams",
            "Between The Sphere",
            "Illusive Duality",
        ],
        "media_bpm": [
            "80",
            "108",
            "120",
            "83",
            "70",
            "80",
            "120",
            "80",
            "70",
            "103",
            "136",
            "90",
            "90",
            "121",
            "100",
            "120",
            "90",
            "100",
            "115",
            "125",
            "112",
            "132",
            "130",
        ],
    },
    {
        "title": "Dub Mates Meeting",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "22,292",
        "comments_count": "30",
        "url": "https://ektoplazm.com/free-music/dub-mates-meeting",
        "img": "https://ektoplazm.com/img/va-dub-mates-meeting-300x300.jpg",
        "tracks": [
            "Water Drops On Engineer Suites",
            "Dubby Tubby",
            "Massive Exode",
            "Yggdrasil",
            "Dubland Mountains",
            "Koran",
            "Intuition",
            "Seeker",
            "Dub From Depths Of The Universe",
            "Kingstoned",
            "Organ",
        ],
        "media_bpm": [
            "80",
            "75",
            "90",
            "70",
            "80",
            "105",
            "70",
            "87",
            "80",
            "82",
            "70",
        ],
    },
    {
        "title": "Brujo’s Bowl – Healing With Sound",
        "styles": ["Bass Music", "Downtempo", "Psy Dub"],
        "download_count": "29,653",
        "comments_count": "41",
        "url": "https://ektoplazm.com/free-music/brujos-bowl-healing-with-sound",
        "img": "https://ektoplazm.com/img/brujos-bowl-healing-with-sound-300x300.jpg",
        "tracks": [
            "Realization Dub",
            "Gyananakashu (The Eye Of Knowledge)",
            "Brujo's Drift",
            "Healing With Sound",
        ],
        "media_bpm": ["80", "80", "80", "80"],
    },
    {
        "title": "Radioactive Sandwich – A World Of Delights",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "18,334",
        "comments_count": "40",
        "url": "https://ektoplazm.com/free-music/radioactive-sandwich-a-world-of-delights",
        "img": "https://ektoplazm.com/img/radioactive-sandwich-a-world-of-delights-300x300.jpg",
        "tracks": [
            "Monkey Hi Five",
            "Goat Herder",
            "Elephant Parade",
            "Walking On Strings",
            "Balls In A Slow",
            "Henowei",
            "The 5th Dementia",
            "Chongo",
            "Pistol Shrimp",
            "Rolling Stone Gathers Dirt",
        ],
        "media_bpm": ["90", "88", "85", "110", "115", "75", "80", "106", "100", "125"],
    },
    {
        "title": "Sunspot – Tales Of The Green Dragon",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "11,793",
        "comments_count": "14",
        "url": "https://ektoplazm.com/free-music/sunspot-tales-of-the-green-dragon",
        "img": "https://ektoplazm.com/img/sunspot-tales-of-the-green-dragon-300x300.jpg",
        "tracks": ["Demanding Happiness", "Experience Expanded", "Grapeyard Shift"],
        "media_bpm": ["78", "73", "85"],
    },
    {
        "title": "Modcam – Six Minute City",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "14,634",
        "comments_count": "18",
        "url": "https://ektoplazm.com/free-music/modcam-six-minute-city",
        "img": "https://ektoplazm.com/img/modcam-six-minute-city-300x297.jpg",
        "tracks": [
            "Six Minute City",
            "Photon Pulse",
            "Expressions Of The Expressionless",
            "Zero Point Field",
            "Grain Season",
            "Sonic Zen",
            "A Walk In The Park",
            "Interlude",
            "Dub Satchel",
            "The Wisdom Cube",
            "Digital Alchemy",
            "The Wisdom Cube",
        ],
        "media_bpm": [],
    },
    {
        "title": "Space Forming Vol. 2",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "19,106",
        "comments_count": "26",
        "url": "https://ektoplazm.com/free-music/space-forming-vol-2",
        "img": "https://ektoplazm.com/img/va-space-forming-vol-2-300x300.jpg",
        "tracks": [
            "...I Still Don't Know Who I Am",
            "Earth",
            "A Passage In Time",
            "Error In Babylon",
            "Squabbling Gods",
            "Mission X",
            "Exorcism",
            "Bem Sol",
            "On A Train To East Malwern",
            "OneFreeMan",
            "Pazzle",
        ],
        "media_bpm": [
            "65",
            "111",
            "90",
            "74",
            "88",
            "115",
            "110",
            "110",
            "97",
            "80",
            "128",
        ],
    },
    {
        "title": "MentalImage – Dreams Vol. 2",
        "styles": ["Downtempo", "Progressive", "Psy Dub"],
        "download_count": "16,063",
        "comments_count": "25",
        "url": "https://ektoplazm.com/free-music/mentalimage-dreams-vol-2",
        "img": "https://ektoplazm.com/img/mentalimage-dreams-vol-2-300x300.jpg",
        "tracks": [
            "Groovy Giant Walking Through His Lands",
            "Uninhabited Planet",
            "Four Elements",
            "Dream Travel To The Other Side Of The Galaxy",
            "Jah!",
            "Altering Dreams",
            "The Dreamer (Part I: Dream Is Destiny)",
            "The Dreamer (Part II: Oneironauts)",
            "The Dreamer (Part III: Tips & Tricks)",
            "The Dreamer (Part IV: Death)",
        ],
        "media_bpm": [
            "120",
            "75",
            "70",
            "140",
            "135",
            "130",
            "120",
            "120",
            "120",
            "120",
        ],
    },
    {
        "title": "Inner Gathering",
        "styles": ["Downtempo", "IDM", "Psy Dub"],
        "download_count": "14,115",
        "comments_count": "10",
        "url": "https://ektoplazm.com/free-music/inner-gathering",
        "img": "https://ektoplazm.com/img/va-inner-gathering-300x300.jpg",
        "tracks": [
            "Somewhere Near",
            "LoveMi",
            "Autumn Leaves",
            "Neon Light",
            "AmbiVALEnt Love",
            "Play Tennis",
            "Cavedwellers",
            "The Behemoth",
            "Deep Reflection",
            "Divinity",
            "Zen Monks Part 1",
        ],
        "media_bpm": ["69", "68", "83", "94", "70", "74", "63", "73", "80", "65"],
    },
    {
        "title": "Harmonic Frequency – Power Of The Flower",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "13,699",
        "comments_count": "25",
        "url": "https://ektoplazm.com/free-music/harmonic-frequency-power-of-the-flower",
        "img": "https://ektoplazm.com/img/harmonic-frequency-power-of-the-flower-300x300.jpg",
        "tracks": [
            "Power Of The Flower",
            "Pink Butterflies",
            "Fractal Forest",
            "Fata Morgana",
            "Sea Of Serenity",
        ],
        "media_bpm": ["92", "100", "80", "100", "85"],
    },
    {
        "title": "Dub For Life",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "16,097",
        "comments_count": "21",
        "url": "https://ektoplazm.com/free-music/dub-for-life",
        "img": "https://ektoplazm.com/img/va-dub-for-life-300x300.jpg",
        "tracks": [
            "Blueprint",
            "Ocean Unknown (Part 2)",
            "Keep On",
            "Sonic Colonic",
            "Green Skins",
            "Chillum Yoga",
            "Grantchester Meadows Remembered",
            "Come A Shore (feat. Sean)",
        ],
        "media_bpm": ["70", "114", "122", "133", "112", "120", "119", "121"],
    },
    {
        "title": "Family Tree",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "15,062",
        "comments_count": "21",
        "url": "https://ektoplazm.com/free-music/family-tree",
        "img": "https://ektoplazm.com/img/va-family-tree-300x300.jpg",
        "tracks": [
            "Purple Magic",
            "Bettie Page",
            "3 Corazones",
            "Good Bye South Africa",
            "Uma (Ode To The Unborn)",
        ],
        "media_bpm": ["104", "95", "85", "70", "105"],
    },
    {
        "title": "Ascoil Sun – Pinnacle Of Coil",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "15,266",
        "comments_count": "26",
        "url": "https://ektoplazm.com/free-music/ascoil-sun-pinnacle-of-coil",
        "img": "https://ektoplazm.com/img/ascoil-sun-pinnacle-of-coil-300x300.jpg",
        "tracks": [
            "Wizard's Magic Haze",
            "Fellows Of The Imagination",
            "Pinnacle Of Coil",
            "Don't Stare At It Too Long",
            "Shapes Being Invented (Interlude)",
            "The Swallowed Sun",
        ],
        "media_bpm": ["68", "110", "123", "110", "100", "110"],
    },
    {
        "title": "Space Forming",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "19,061",
        "comments_count": "23",
        "url": "https://ektoplazm.com/free-music/space-forming",
        "img": "https://ektoplazm.com/img/va-space-forming-300x300.jpg",
        "tracks": [
            "Praying Mantis",
            "Blue Home",
            "Sweet",
            "Night Shore Walk",
            "Paranormaloid",
            "Running, Forgetting...",
            "Hemp Street 303",
            "Egyptian DendroToxiDrone",
            "Trip Complete",
            "Mashala Dub",
            "7 01",
        ],
        "media_bpm": [
            "90",
            "60",
            "110",
            "100",
            "100",
            "120",
            "120",
            "90",
            "104",
            "76",
            "110",
        ],
    },
    {
        "title": "Globular – Colours Of The Brainbow",
        "styles": ["Downtempo", "Psy Dub"],
        "download_count": "23,901",
        "comments_count": "45",
        "url": "https://ektoplazm.com/free-music/globular-colours-of-the-brainbow",
        "img": "https://ektoplazm.com/img/globular-colours-of-the-brainbow-300x300.jpg",
        "tracks": [
            "The Continuum Process",
            "Colours Of The Brainbow",
            "Synesthesiasia",
            "And On The Carefree Shores Of Dub...",
        ],
        "media_bpm": ["70", "106", "123", "84"],
    },
]
